### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by squideyes** [mingyaulee/Blazor.BrowserExtension.Samples#8]
I downloaded a fresh copy of the repo and then followed the instructions under [](https://github.com/mingyaulee/Blazor.BrowserExtension/issues/179) but I still got the following errors.  I'm using VS2022 Version 17.12.0 (the one with .NET9, but I also have Microsoft SDK Version 8.0.404 installed.

I really want to use the SidePanel so I'm hoping this can be fixed soon.

Thanks for your great work...

The "ApplyCompressionNegotiation" task failed unexpectedly.
System.InvalidOperationException: Fingerprint for 'C:\Users\trader\Desktop\Blazor.BrowserExtension.Samples-main\Messaging\src\obj\Debug\net8.0\browserextension\build\BackgroundWorker.js' is not defined.
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
The "ApplyCompressionNegotiation" task failed unexpectedly.
System.InvalidOperationException: Fingerprint for 'C:\Users\trader\Desktop\Blazor.BrowserExtension.Samples-main\Sidepanel\src\obj\Debug\net8.0\browserextension\build\browserextension.config.json' is not defined.
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
The "ApplyCompressionNegotiation" task failed unexpectedly.
System.InvalidOperationException: Fingerprint for 'C:\Users\trader\Desktop\Blazor.BrowserExtension.Samples-main\SidebarUsingIframe\src\obj\Debug\net8.0\browserextension\build\browserextension.config.json' is not defined.
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
The "ApplyCompressionNegotiation" task failed unexpectedly.
System.InvalidOperationException: Fingerprint for 'C:\Users\trader\Desktop\Blazor.BrowserExtension.Samples-main\SidebarUsingContentScripts\src\obj\Debug\net8.0\browserextension\build\browserextension.config.json' is not defined.
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
The "ApplyCompressionNegotiation" task failed unexpectedly.
System.InvalidOperationException: Fingerprint for 'C:\Users\trader\Desktop\Blazor.BrowserExtension.Samples-main\NewTabPage\src\obj\Debug\net8.0\browserextension\build\browserextension.config.json' is not defined.
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by mingyaulee** [comment]
Does adding a `global.json` config to force using .Net 8 work?

**Comment by squideyes** [comment]
No!

Her’s my global .json, which I’ve added to the same folder as Sidpanel.csproj:

{
  "sdk": {
    "version": "8.0.404"
  }
}

I’m using the latest VS2022.

Thanks for your help….

**Comment by iikuzmychov** [comment]
I encountered the same problem just now using .NET 8

**Comment by adprevost** [comment]
I also encounter the same error with the latest VS Version 17.12.1. I'm getting the error message in both  .Net 8 and .Net 9 new projects.

**Comment by southgate-rob** [comment]
I encountered the same issue and can confirm using the global.json file worked.  I used the following command to generate it:
`dotnet new globaljson --sdk-version 8.0.307`
Ran it in the same directory as the solution file and restart visual studio.

**Comment by bradleyables22** [comment]
I tried southgate-rob's fix but sdk 9.0.100 which i got from running dotnet --version and it did not fix the problem. Prior to finding this thread I opened another on the actual package repo itself.

**Comment by southgate-rob** [comment]
@bradleyables22 you need to set the SDK version to a .NET 8 version as the error is caused by the .NET 9 SDK as far as I understand it anyway.

**Comment by mingyaulee** [comment]
This should be fixed now if you upgrade the version of `Blazor.BrowserExtension` to `v2.0.2`. I am currently working on changing the target framework for the package to .Net 9 & 8, once that is done I will upgrade the version in this repo.
